filename: aci-doc.xlsx
tabs:
  Applications:
    class: fvAp
    headers: [Name, Distinguished Name]
    properties: [name, dn]

  # Audit Logs:
  #   class: aaaModLR
  #   properties: [dn, id, affected, user, severity, descr, created, cause, changeSet]
  # Endpoints:
  #   class: fvCEp
  #   properties: [lcC, ip, mac, encap]
  # Faults:
  #   class: faultInst
  #   properties: [ack, code, severity, delegated, descr, domain, type]
  Subnets:
    class: fvSubnet
    properties: [name, ip, scope]
  Switches:
    class: fabricNode
    properties: [name, role, fabricSt, serial, vendor, id]
  Tenants:
    class: fvTenant
    properties: [name, dn]
  Topology:
    class: lldpAdjEp
    properties: [dn, capability, chassisIdT, chassisIdV, id, mgmtIp, portDesc, portIdT,
      portIdV, sysName, sysDesc]
  Interface Errors:
    class: rmonDot3Stats
    headers: [Interface Name, Alignment Errors, Carrier Sense Errors, FCS Errors, Ingress Pause Frames]
    properties: [dn, alignmentErrors, carrierSenseErrors, fCSErrors, inPauseFrames]
